<?php

namespace RestBundle\Repository;

/**
 * CommrntaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommrntaireRepository extends \Doctrine\ORM\EntityRepository
{
}
